[tool.poetry]
name = "blacklight"
version = "0.1.0"
description = "A package to manage genetic deep learning dependencies in python."
authors = ["Cole Agard <ctagard19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
pandas = "^1.5.3"
tensorflow_macos = {version = "*", markers = "platform_machine == 'arm64'"}
tensorflow_metal = {version = "*", markers = "platform_machine == 'arm64'"}
tensorflow = {version = "*", markers = "platform_machine != 'arm64'"}

[tool.poetry.group.test.dependencies]
fastparquet = "*"
openpyxl = "*"

[tool.poetry.group.dev.dependencies]
flake8 = "*"
autopep8 = "*"
tensorflow_macos = {version = "*", markers = "platform_machine == 'arm64'"}
tensorflow_metal = {version = "*", markers = "platform_machine == 'arm64'"}
tensorflow-intel = {version = "<2.11", markers = "platform_machine != 'arm64'"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
