name: test
on: [push]
env:
  MAX_LINE_LENGTH: 110

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E501,W503,W504,F401 --show-source --statistics blacklight/
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
    
      - name: Test package with unittest 
        run: |
          ls
          pwd
          pip install setuptools>=42.0.0
          pip install pandas numpy pyarrow fastparquet openpyxl scikit-learn
          pip install tensorflow 
          python -m unittest discover